before_script:
  - yarn install

cache:
  paths:
  - node_modules/

stages:
  - test
  - build
  
test:
  image: node:10
  stage: test
  script:
   - yarn test
   - yarn prod
  tags:
   - docker
 
 build:
  image: node:10
  stage: build
  script:
   - yarn prod
  tags:
   - docker