cache:
  paths:
  - node_modules/

stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: node:10
  script:
   - yarn install
   - yarn test
  tags:
   - docker

build:
  stage: build
  image: node:10
  script:
   - yarn install
   - yarn prod
  tags:
   - docker
  artifacts:
    paths:
      - public/
      
deploy:
  stage: deploy
  image: docker:dind
  script:
   - apk add --no-cache curl jq python py-pip
   - pip install awscli
   - $(aws ecr get-login --no-include-email --region us-east-1)
   - docker build -t jtbsearch .
   - docker tag jtbsearch:latest 579318172733.dkr.ecr.us-east-1.amazonaws.com/jtbsearch:latest
   - docker push 579318172733.dkr.ecr.us-east-1.amazonaws.com/jtbsearch:latest
  tags:
   - docker
  dependencies:
    - build    
      