cache:
  paths:
  - node_modules/

stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: node:10
  script:
   - yarn install
   - yarn test
  tags:
   - docker

build:
  stage: build
  image: node:10
  script:
   - yarn install
   - yarn prod
  tags:
   - docker
  artifacts:
    paths:
      - public/
      
deploy:
  stage: deploy
  image: docker
  script:
   - echo "tetstetstets"
  tags:
   - docker
  dependencies:
    - build    
      