before_script:
  - yarn install

cache:
  paths:
  - node_modules/

stages:
  - test
  - build

test:
  stage: test
  image: node:10
  script:
   - yarn test
  tags:
   - docker

build:
  stage: build
  image: node:10
  script:
   - yarn prod
  tags:
   - docker
